# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Académie Ryfacto
lang: fr
description: >- # this means to ignore newlines until "baseurl:"
  Fais passer l'architecture de ton app iOS au niveau supérieur !
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://academie.ryfacto.fr" # the base hostname & protocol for your site, e.g. http://example.com
social_source: "academie.ryfacto.fr"
twitter_username: ryfacto_fr
comment_email: commenter@academie.ryfacto.fr
author: Nicolas Verinaud
author_email: nicolas.verinaud@ryfacto.fr
author_gravatar: https://www.gravatar.com/avatar/c96c4b5a2307be068f13feea782f4afe?s=300
defaults:
  -
      scope:
        path: "" # all paths
      values:
        image:
          path: /images/logo.jpg
          width: 300
          height: 89
        excerpt_separator: <!--more-->
collections:
  advanced-ios-craft:
    output: true
feed:
  path: ""

# Build settings
markdown: kramdown
theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
